### ISSUE TITLE
Questions about pcb

### ISSUE THREAD

**Issue by nobodyisinocent** [jasonsbeer/Amiga-2000-ATX#10]
Hello,

I have downloaded the Kicad project. What you have done is really great !
There are some holes which are not connected like the Int6 signal onto the Zorro slots.
The 3v3 pins of the power connector are not connected also.

Is it normal that there are some missing tracks  as shown in the pictures below ?

Int6 signal:
![image](https://user-images.githubusercontent.com/80821708/129476324-183a2bfc-3805-4091-9a0c-e702563c73da.png)

3v3 signal:
![image](https://user-images.githubusercontent.com/80821708/129476345-8ae7ca9c-a75a-41d8-a895-02ab3ca4a086.png)

Kind regards,
Franck

**Comment by nobodyisinocent** [comment]
To be conform to the schematics, the Int6 holes should be connected. Something like that: :-)

![Uploading image.png…]()

**Comment by nobodyisinocent** [comment]
I assume you used Freerouting for generating the tracks.
This software is excellent, but the optimization batch can have some weaknesses.
Like the original tracks dispositions on CN600 for example. On the left the automatic rooting, and on the right a manual modification of the tracks.

![image](https://user-images.githubusercontent.com/80821708/129479613-4ab43107-1d0a-439c-9037-9998e005b28d.png)

I'm actually trying to optimize the pcb of your fantastic project ! :-)

**Comment by nobodyisinocent** [comment]
A little work of rooting optimization around U102.
Here, the original rooting:
![image](https://user-images.githubusercontent.com/80821708/129479984-2e9953ac-3664-4edf-97ce-ea141da2fb16.png)

Here, the modified rooting:
![image](https://user-images.githubusercontent.com/80821708/129480012-b16e04dc-28fa-4e42-bda5-982d6c168f80.png)

**Comment by nobodyisinocent** [comment]
Around beautiful ANGUS ! :-)
Before:
![image](https://user-images.githubusercontent.com/80821708/129480129-bcbd995c-54af-4097-a2cf-e70f6227a465.png)

After:
![image](https://user-images.githubusercontent.com/80821708/129480142-b7c61e9d-0df1-4bd3-a0be-7ec49660d8e6.png)

**Comment by jasonsbeer** [comment]
The _INT6 signal is connected correctly in the supplied files. Perhaps something was disconnected during your optimization work.

![INT6](https://user-images.githubusercontent.com/78610265/129495065-18fb6643-e6ff-4967-af53-67493e33e99c.png)

The 3.3V taps don't need to be tied together. I probably should have removed them from the schematic, but chose to ignore them instead. Only X2 uses 3.3V and that's connected properly. So, it is as expected.

The board is completely routed by hand. I did not take the time to review everything for optimization. My thought, if it works, let it be. I'll look at your suggestions for consideration in a possible future revision. Thanks
