### ISSUE TITLE
EMI filters

### ISSUE THREAD

**Issue by Pragakhan09** [jasonsbeer/Amiga-2000-ATX#15]
Hi, 
first of all, @jasonsbeer thank you for this wonderful project ! I'm going to build one but I see that those EMI filters (W3F11A1018AT1F) are not available. Can someone suggest a 1206 form factor alternative ? I'm wondering if the 0805 form factor ‎101X15N101MV4E‎ would fit ?
Kind regards

**Comment by jasonsbeer** [comment]
If you can't find the exact part, you can try part NFE31PT101C1E9L. Its a bit odd looking, but is the correct footprint.

I would avoid using the 0805 part. You can probably get it to work if you place just perfect, but are likely to have trouble with consistent solder joints.

**Comment by Pragakhan09** [comment]
Great, thanks for your answer. I looked at that part but like you say it's a bit odd looking and has a few different specs (25v...). I'll implement those :-)
