### ISSUE TITLE
Tick signal

### ISSUE THREAD

**Issue by seb132** [jasonsbeer/Amiga-2000-ATX#9]
Hello Jason - what a nice project you did here!
How is the tick signal dealt with ? I see you recommend a standard ATX PSU, and you mention how the -5V is generated but what about the tick signal ? Is it onboard too ? Thanks ! (might not be an issue, after all... haha)

**Comment by jasonsbeer** [comment]
TICK is replaced by _VSYNC from Agnus. This is how it's done on the Amiga 500 and jumper J300 can set this on the original Amiga 2000. I will add a comment to the build page about this.
